name: mobsfscan ios
on:
  push:
    paths:
      - 'MobSF-iOS/**'

# GITHUB_TOKENの権限を設定できる
permissions:
  security-events: write # sarifファイルをアップロードするのに必要

jobs:
  mobsfscan:
    runs-on: ubuntu-latest

    name: mobsfscan code scanning
    
    steps:
      - name: Checkout the code
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        - with:
          python-version: 3.7

      - name: Set up MobSF
        run: |
          pip3 install --upgrade mobsfscan
    
      - name: Run mobsfscan
        run: |
          mobsfscan MobSF-iOS --sarif --output results.sarif || true

      - name: gzip
        run: |
          gzip -c results.sarif | base64 -w0

      # https://docs.github.com/ja/rest/code-scanning#upload-an-analysis-as-sarif-data
      - name: Upload mobsfscan report
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -F results.sarif \
            https://api.github.com/repos/Tatsumi0000/MobSF-Practice/code-scanning/sarifs
